#!/usr/bin/env python3

import gridstat
import logging
import sys
import systemstattool


class GridStatTool(gridstat.GridStat, systemstattool.SystemStatTool):
    def __init__(self, logfile="gridstat.log", **kwargs):
        super(GridStatTool, self).__init__(logfile=logfile)

        self.logger = logging.getLogger(__name__)

        self.command_parser.add_argument(
            "--nodes",
            help="total number of Selenium Grid nodes",
            action="store",
            dest="nodes",
            default=2,
            type=int,
        )

        self.command_parser.add_argument(
            "--url",
            help="url of the Selenium Grid server being waited on",
            action="store",
            dest="url",
            default="http://localhost:4444",
            type=str,
        )

        # parse command line and config file options
        self.parse_options()

        # override GridStat class defaults with command line defaults
        self._url = self.options.url
        self._nodes = self.options.nodes

        # start logging
        self.start_logging()


if __name__ == "__main__":

    tool = GridStatTool()

    tool.logger.info("checking status of {}".format(tool.options.url))

    system_ready = tool.wait_until_ready()

    if system_ready:
        status = 0
    else:
        status = 1

    tool.logger.debug("exiting")

    sys.exit(status)
