#!/usr/bin/env python3

import sutstat
import logging
import sys
import systemstattool
import os


class SutStatTool(sutstat.SutStat, systemstattool.SystemStatTool):

    def __init__(self, logfile='sutstat.log', **kwargs):
        super(SutStatTool,self).__init__(logfile=logfile)

        self.logger = logging.getLogger(__name__)

        self.command_parser.add_argument(
            "--url",
            help="url of the sut server being waited on",
            action="store",
            dest="url",
            default="http://localhost:6969",
            type=str)

        # parse command line and config file options
        self.parse_options()

        # override SutStat class defaults with command line defaults
        self._url = self.options.url

        # start logging
        self.start_logging()


if __name__ == '__main__' :

    tool = SutStatTool()

    tool.logger.info('checking status of {}'.format(tool.options.url))

    system_ready = tool.wait_until_ready()

    if system_ready:
        status = 0
    else:
        status = 1

    tool.logger.debug('exiting')

    sys.exit(status)
