#!/usr/bin/env bash
set -o errexit
set -o pipefail

main() {
  local container_name="${1}"
  if [[ ! "${container_name}" ]]; then
    : 'ERROR: missing <container-name> positional arg'
    exit 86
  fi

  local wait_start
  wait_start="$(date +%s)"
  local wait_end
  local attempt=0

  while true; do
    local health_status
    health_status="$(
      docker inspect --format='{{.State.Health.Status}}' "${container_name}"
    )"
    if [[ "${health_status}" == healthy ]]; then
      wait_end="$(date +%s)"
      echo
      echo 'SUCCESS: Waited '$((wait_end - wait_start))'s'
      exit 0
    fi
    attempt=$((attempt + 1))
    if [[ "${attempt}" -gt 60 ]]; then
      wait_end="$(date +%s)"
      echo
      echo 'ERROR: timeout waiting for container health;' \
        'waited '$((wait_end - wait_start))'s' >&2
      exit 42
    fi
    echo -n .
    sleep 1
  done
}

main "${@}"
