site_name: 'rsconnect-jupyter User Guide'
copyright: Posit Software, PBC. All Rights Reserved

# We activate GA only when hosted on our public docs site
# and not when installed.
#
# See overrides/partials/integrations/analytics.html
google_analytics:
  - 'UA-20375833-3'
  - 'auto'

nav:
- 'Installing': 'index.md'
- 'Upgrading': 'upgrading.md'
- 'Usage': 'usage.md'
- 'Collaboration': 'collaboration.md'
- 'Uninstalling': 'uninstalling.md'
- ──────────────: separator.md
- 'Additional Resources': 'additional.md'
- 'Release Notes': 'NEWS.md'

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"
  - attr_list: {}
  - def_list: {}
  - tables: {}
  - pymdownx.superfences: {}
  - codehilite:
      guess_lang: false
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets:
      base_path: 'docs/'
      check_paths: true

plugins:
  - search:
      separator: '[\s\-\.]+'
  - macros

theme:
  name: material
  custom_dir: overrides
  font:
    text: Open Sans
  logo: 'images/iconPositConnect.svg'
  favicon: 'images/favicon.ico'
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - css/external-links.css
  - css/superfences-tabs.css
  - css/custom.css

extra_javascript:
  - js/custom.js

extra:
  search:
    tokenizer: '[\s\-\.]+'
