name: snyk
on:
  schedule:
    - cron: "0 10 * * 1" # Monday @ 10am UTC
  workflow_dispatch:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SNYK_ORG: rstudio-connect

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Pipfile.lock dependencies
        run: pipenv sync

      - name: Run Snyk
        uses: snyk/actions/python@master
        with:
          command: monitor
          args: --file=Pipfile --org=${{ env.SNYK_ORG }}
