name: snyk
on:
  schedule:
    - cron: "0 10 * * 1" # Monday @ 10am UTC
  workflow_dispatch:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SNYK_ORG: rstudio-connect

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Snyk
        uses: snyk/actions/python@master
        with:
          command: monitor
          args: --file=requirements-dev.txt --package-manager=pip --project-name=rsconnect-jupyter --org=${{ env.SNYK_ORG }}
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Snyk
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --file=yarn.lock --project-name=rsconnect-jupyter --org=${{ env.SNYK_ORG }}
